volumes:
  vscode-extensions:

networks:
  default:  
    driver: bridge
    driver_opts:
        com.docker.network.bridge.enable_ip_masquerade: 'false'


services:
  forwarded_auth_dev:
    extends:
      file: ../docker-compose.yaml
      service: forwarded_auth
    env_file: ../.env
    environment:
      - NODE_ENV=development
      - NODE_OPTIONS=""
    networks: !override
      - default
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - vscode-extensions:/root/.vscode-server/extensions
      - ../:/app:cached
    command: /bin/sh -c "while sleep 1000; do :; done" 


  traefik_dev:
    image: traefik:latest # v2.6
    container_name: traefik_dev
    restart: unless-stopped
    networks:
      - default
    ports:
      - 80:80
      - 443:443
    # network_mode: host # needed to get x-real-ip for client
    env_file: ../.env
    environment:
      - TZ=America/Denver
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command:
      - --log.level=DEBUG
      - --log.format=common
      - --accessLog.filters.statusCodes=400-499
      - --accessLog.filePath=/var/log/access.log
      - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
      - --entrypoints.web.forwardedHeaders.trustedIPs=${TRUSTED_HEADER_SOURCE_IPS}
      - --entrypoints.websecure.address=:443
      - --entrypoints.websecure.http.tls=true
      - --entrypoints.websecure.forwardedHeaders.trustedIPs=${TRUSTED_HEADER_SOURCE_IPS}

  dummy_site:
    image: nginx
    container_name: dummy_site
    restart: unless-stopped
    networks:
      - default
    ports:
      - 81:80
    env_file: ../.env
    environment:
      - TZ=America/Denver
    volumes:
      - /etc/localtime:/etc/localtime:ro
    logging:
      driver: json-file
      options:
        max-size: "250m"
        max-file: "10"
    depends_on:
      - traefik_dev    
    labels: # https://stackoverflow.com/questions/58356714/how-to-redirect-http-to-https-with-traefik-2-0-and-docker-compose-labels
      - com.centurylinklabs.watchtower.enable=false
      - traefik.enable=true
      - traefik.docker.network=forwarded-auth_devcontainer_default

      - traefik.http.middlewares.middlewares-chain.chain.middlewares=test-auth@docker,robots-header@docker

      - traefik.http.routers.dummy_site-server-unsecure.middlewares=middlewares-chain
      
      - traefik.http.routers.dummy_site-server-unsecure.rule=Host(`${ACME_TEST_DOMAIN}`)
      - traefik.http.routers.dummy_site-server-unsecure.entrypoints=web
      - traefik.http.routers.dummy_site-server-unsecure.service=dummy_site-server      

      - traefik.http.middlewares.test-auth.forwardauth.authRequestHeaders=cookie,${ALLOW_IP_NO_CREDENTIALS_TRUSTED_HEADERS}
      - traefik.http.middlewares.robots-header.headers.customresponseheaders.X-Robots-Tag=noindex,nofollow,nosnippet,noarchive,notranslate,noimageindex # prevent Google from indexing service
      - traefik.http.routers.dummy_site-server.middlewares=middlewares-chain

      - traefik.http.routers.dummy_site-server.rule=Host(`${ACME_TEST_DOMAIN}`)
      - traefik.http.routers.dummy_site-server.service=dummy_site-server
      - traefik.http.services.dummy_site-server.loadbalancer.server.port=80
      - traefik.http.routers.dummy_site-server.entrypoints=websecure
      
      # Set up forwarded auth server
      - traefik.http.middlewares.test-auth.forwardauth.address=http://forwarded_auth:${SERVER_PORT}/auth?X-Redirect-On-Auth-Fail-URL=https://reddit.com?from-label&cookie_domain=${ACME_TEST_DOMAIN}
      - traefik.http.middlewares.test-auth.forwardauth.authResponseHeaders=none
      - traefik.http.middlewares.test-auth.forwardauth.addAuthCookiesToResponse=${COOKIE_NAME:-forwardAuth}
